### ISSUE TITLE
Trouble getting it to work in the system The One Ring 2E

### ISSUE THREAD

**Issue by cwlithgow** [coffiarts/FoundryVTT-crunch-my-party#2]
Successfully run the group macro to create party #1. However the Toggle macro then returns this:

![image](https://github.com/coffiarts/FoundryVTT-crunch-my-party/assets/85030999/3b6c3c9e-0e14-4f1f-8d98-ceffa6e74cbc)

& the console shows this:

![image](https://github.com/coffiarts/FoundryVTT-crunch-my-party/assets/85030999/854e45f7-6b39-4a1d-9bed-5d035614bc64)

**Comment by coffiarts** [comment]
Sorry to hear that you're having trouble with the macro - and thanks for already providing the helpful details.
I'll investigate.

The following additional information from your side might also help:

**1.) What does "Tor2eTokenDocument" in your log stand for?**
I don't have this in my logs, so I assume it is another module?

**2.) Which token names does your group #1 definition consist of?**
E.g. you could give me a screenshot of your module settings, like this:
![image](https://github.com/coffiarts/FoundryVTT-crunch-my-party/assets/39616483/2467d384-47ed-4ce7-8253-c1061608e17b)

**3.) What does your console return when entering the following?**

`canvas.tokens.ownedTokens.find(t => t.name.toLowerCase() === "<your group member name>")`

... where `<your token name>` needs to be replaced by each entry from your names list from 2.). Do not forget to check for the group token as well!

It should (as in my example with "bolgg") return like this (and **not** "undefined"):
![image](https://github.com/coffiarts/FoundryVTT-crunch-my-party/assets/39616483/fab83dc0-7ee3-4308-a172-b1042b9c27bc)

**Comment by coffiarts** [comment]
I've just installed myself a fresh Tor2e world and ran a quick test. Works fine on my side. So doesn't look to me like a genereal incompatibility with this system yet:
https://github.com/coffiarts/FoundryVTT-crunch-my-party/assets/39616483/7627b434-0f95-4322-9fb1-8cc2a5a09fdb

So I am curious to see your answers to my questions above.

**Comment by cwlithgow** [comment]
Thanks for your time coffiarts! it is begining to sound like a module incompatibility I should have checked for first. Here is what I find from your questions above:

1. Tor does indeed stand for The One Ring. I don't know enough to know exactly what part of things Tor2eTokenDocument refers to.
2. 
![image](https://github.com/coffiarts/FoundryVTT-crunch-my-party/assets/85030999/18adf258-d40d-4046-894f-689f4353656e)
3. 
![image](https://github.com/coffiarts/FoundryVTT-crunch-my-party/assets/85030999/d2e93d04-c4c8-4ee6-bde4-3b11ab2dad5b)



I look forward to your findings. In the mean time I'll experiment a bit with disabling other modules to see if I can find an incompatability there.

Thanks!

**Comment by cwlithgow** [comment]
Just tested on my own clean test world as well...works fine so it must be a module incompatability. I'll play around with disabling modules until I find the culprit. I should have done that first - but thanks for the time looking into it for me!

**Comment by coffiarts** [comment]
Don't worry, it is also very helpful for me to understand the issue. Given that we should find the "culprit" module, I can try to install it on my side, reproduce the isse, and possible create a compatibility fix.
For now, it looks to me like some mod is replacing dnd5e's Token5e class by Tor2eToken. Maybe that class somehow replaces the tokens at runtime, so that they have different ids?
Looking forward for news.

**Comment by cwlithgow** [comment]
So..interesting....I ran through my modules using "Find the Culprit" module and it placed the blame on Mass Edit. However, after resetting everything (including turning Mass Edit back on) your module is doing exactly what it is supposed to. I guess you can't account for entropy...plus Mass Edit did get a update today which may have randomly fixed it. In any case....thanks for your consideration and I look forward to using this module!

**Comment by cwlithgow** [comment]
Found additional information. The issue seemingly cropped up again..and it seems that the issue is that the macro won't work if the scene isn't active. If you have one scene active, navigate to a second without activating it, and try the macro on the same party - thats when it throws the error. It was more of my workflow than a module issue. I think at least. I'll comment more if I notice anything else.

**Comment by coffiarts** [comment]
Your so absolutely right for spotting this! Other than expected, this has nothing to do with Tor2e in general, or that mysterious Tor2eToken class. It is simply a stupid, system-agnostic bug in my module!
With your information I could implement and rollout a fix within minutes: https://github.com/coffiarts/FoundryVTT-crunch-my-party/blob/master/CHANGELOG.md#1106
Credits to you given in the release info 👍
