### ISSUE TITLE
V12 Compatibility 

### ISSUE THREAD

**Issue by CasualTerror** [coffiarts/FoundryVTT-crunch-my-party#6]
Any chance of V12 compatibility? I just discovered this module and it's great for my group as we are small and my players usually have to run multiple characters to cover all the specializations of 5E

**Comment by coffiarts** [comment]
Hi there, don't worry, I am already on it. Just wanted to give it some more time until the first v12 smokes have settled down. But I realize that everybody wants to go for it now.
From my very first tests with v12 I assume thar it _is_ already compatible and probably only needs the declarative adjustments in module.json (so people might want to give ot their own try already by simply hacking modules.json).
IAnyway, I expect to be able to deliver the official upgrade by the upcoming weekend.

**Comment by coffiarts** [comment]
It is done: https://github.com/coffiarts/FoundryVTT-crunch-my-party/releases/tag/12.0.0
