### ISSUE TITLE
Optional permissions

### ISSUE THREAD

**Issue by OregonPinkRose** [coffiarts/FoundryVTT-crunch-my-party#8]
I would be ecstatic if I could choose which permission level could execute the macro or Hot Key.

**Comment by coffiarts** [comment]
Hi there, thanks fior asking. I'll have a look at it asap.
What game system are you on? dnd5?

**Comment by coffiarts** [comment]
@OregonPinkRose - As you specifically mentioned "permission **_level_**", I am assuming that you are not simply thinking of this?
![image](https://github.com/user-attachments/assets/7ec64bb6-7a08-44aa-a4cd-264ab31e898a)
![image](https://github.com/user-attachments/assets/0a411a0a-69a3-4fc1-a6f4-f33ebb80c4d1)
Or is it that simple?
I guess what you have in mind is not about assigning ownership per each _individual_ player, but rather like in the User Management here, right?
![image](https://github.com/user-attachments/assets/1086f9b4-efb4-46d6-a069-7aea27b92772)

**Comment by OregonPinkRose** [comment]
Hmmm. That might work. 
But yes, I was thinking of the latter. I want to give a player the option to move the whole group.

**Comment by coffiarts** [comment]
Thanks for the clarification.
Now I am not sure anymore whether we're talking about the same thing here.
When you say move the "whole group", are you referring to the group token ("collapsed" state, as my mod calls it), or the individual actor tokens ("exploded" state)?
And by "move": Do you mean just moving those icons around in the scene (which is basic game functionality and has nothing to do with my mod)? Or do you mean to allow a player to trigger the "collapsing/exploding" between single token and group token state?

**Comment by OregonPinkRose** [comment]
For me, it would be helpful if the player could collapse the party. We play in-person and one player moves all tokens during combat, and then if they could collapse it and move to the next room and explode, that would be great.

**Comment by coffiarts** [comment]
Ok, that makes absolutely sense. But wouldn't the simple solution be to just assign ownership both for the "toggle" macro and the group token to that specific player? What else could my mod do to make it even easier?

**Comment by OregonPinkRose** [comment]
That all makes sense. I was reading the mod and trying it out and thought it was only available for the DM. 
But yeah, all that does exactly what I want. Thanks for the time, and the mod.

**Comment by coffiarts** [comment]
Happy to hear that! Enjoy the crunching! :-)
